import type { Metadata } from "next";
import { Inter, Rubik_Glitch } from 'next/font/google'
import "../globals.css";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { hasLocale } from "next-intl";
import { routing } from "../../i18n/routing";
import { setRequestLocale, getMessages } from "next-intl/server";

const inter = Inter({
  subsets: ["latin"],
});

const rubik_glitch = Rubik_Glitch({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
params: Promise<{ locale:string }>;};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) return notFound();

  setRequestLocale(locale);
  const messages = await getMessages();

  return (
    <html lang= {locale} className={inter.className}>
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider messages={messages}>
        {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
